spring:
  datasource:
    url: jdbc:sqlserver://utdcapstonedb.database.windows.net:1433;database=growing-tree;user=sqldbadmin@utdcapstonedb;password=Capstone12!;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: sqldbadmin@utdcapstonedb
    password: Capstone12!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    tomcat:
      validation-query: SELECT author from EVENTS

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    com.utdallas.capstone.*: debug
    com.utdallas.capstone.mapper.*: debug;


server:
  port: 8086

envconfig:
  properties:
    authorizedUsers: usmannaruhina@gmail.com,iusmankhalid7@gmail.com
    clientSecret: O0EAAtiEvb6RJljSB0d8Krhf0so4DDriq69W8x0Ts8Mtr3Uc0dovo7cVdrB-5jL7


